[package]
name = "tucan-search"
version = "0.1.0"
authors = ["Christian Friedow <christian@friedow.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.15.1"
gio = "0.15.1"
glib = "0.15.1"
pango = "0.15.1"
gtk4 = "0.4.6"

walkdir = "2"
subprocess = "0.2.8"
json = "0.12.4"
